remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: Corey Gaspar | CS 499 Computer Science Capstone
description: A professional ePortfolio demonstrating my growth and application of computer science principles through software engineering and design, algorithms, databases, and security.
